### ISSUE TITLE
Disable database management from Odoo

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#215]
https://www.nytimes.com/2016/08/06/arts/this-is-fine-meme-dog-fire.html

**Comment by gabrielcossette** [comment]
@EricDube We could do the following:

- Create database
- Edit this line in odoo.conf: `list_db = False`
- Restart container

And revert the change if we need to reset/backup the database.
Does that sound good?

**Comment by EricDube** [comment]
@gabrielcossette Since this is the only thing we need for the config for we should use the launch argument instead which does the same thing. We just have to set it in the Dockerfile.

**Comment by jaysonmc** [comment]
@EricDube @gabrielcossette 

To do it in the dockerfile we'd have to do it via env variable (to not push the password to source control). So I we would need to agree on the variable and set it on k8 as well, I imagine

Someone correc me if Im wrong, not super familiar with our setup

**Comment by EricDube** [comment]
@jaysonmc this is just to disable the database list. The password for Master can be set on initial setup and then forgotten about until we have more time to cleanly build configs.

**Comment by gabrielcossette** [comment]
@EricDube I think it would be easier to add the argument to the odoo.conf that is copied in the image. This way, we can modify it in the running container and restart it if we need to. Otherwise, we would need to build a new image.

So the way it would work:

1. Database access disabled by default in odoo.conf of image
2. If we need to enable it (e.g., set up a new instance), we connect to command-line inside the running container, modify the argument in odoo.conf, and restart the container
3. We create the database and then repeat step 2.

I'll submit a PR and we can discuss there if another approach is preferred.
