### ISSUE TITLE
Basic user guide

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#33]
- [ ] Add user/employee
- [ ] Login
- whatever other required basic functionality you can find

**Comment by floo0025** [comment]
Basic outline done. Need the data models, CLF, and prod instance to be stable before I can go much further. Screenshots are not possible at this time

**Comment by floo0025** [comment]
User manual and support manula, v1, are up at https://drive.google.com/drive/folders/1YYTkeaX9ClkP2UduWZHt7lgEGVu1xCML

These are rough and need refinement because they're based off of an early version of dev, but the process should be nearly identical. I added way more to support than they expected, but from the perspective of, say, TFS administration all of the extra topics will be relevant.

Once the data models and custom fields are finalized I can move forward with a more detailed data import section. And once the CLF is in we can move forward with screenshots, and subsequently organizing the docs with sections, numbering, etc.

**Comment by jaysonmc** [comment]
For the user manual on the last page, could we please update the screenshot? We removed the modal view and went with just the list view, as I dont use a good use case for the panel view for our users.

Thanks. They look great! We'll aim to run them by some users in the near future.

**Comment by floo0025** [comment]
@jaysonmc All screenshots will be updated. I've been holding off on screenshots until the UI and fields were finalized and CLF was applied

**Comment by floo0025** [comment]
User Manual
https://drive.google.com/open?id=1Qogc-FIUV_OSQRpUFCIWE1RFmRozELQy
