### ISSUE TITLE
Technical guide 

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#34]
- [ ] How importa data (employee data would be first priority)

**Comment by floo0025** [comment]
Basic outline done. Need the data models, CLF, and prod instance to be stable before I can go much further. Screenshots are not possible at this time

**Comment by jaysonmc** [comment]
@floo0025 , is it in the Google drive?

**Comment by floo0025** [comment]
@jaysonmc O365 at the moment. Using Word for a large technical doc, but Google drive isn't accessible from the ESDC network. Back to it tomorrow. Import is pretty straightforward, but the models and CLF have to be finalized. Wording will change as well, and screenshots will be included:

**Import Data** 

Employee data can be imported into the system using CSV (.csv) or Excel (.xlsx) files. 

Note: Based on inferences from GitHub issues, this is going to change dramatically as custom fields are added and others are deleted and/or modified. The basic process should be relatively similar, but there is little value documenting it until the data models are stable. 

1.     Go to Employees 
2.     Click the “Import” button 
3.     Go to Employees 
4.     Click the “Import” button 
5.     Click the “Load File” button 
6.     Select the fileClick the “Load File” button 
7.     Select the file 

You can practice by using a prepopulated dataset: 

1.    Go to Employees 
2.    Click the “Import” button 
3.    Click “Import Templates for Employees” 
4.    Save the file locally 
5.    Follow the import steps above 

References 
https://www.odoo.com/documentation/user/13.0/general/base_import/import_faq.html 
https://www.odoo.com/documentation/user/13.0/general/base_import/adapt_template.html

**Comment by floo0025** [comment]
User manual and support manula, v1, are up at https://drive.google.com/drive/folders/1YYTkeaX9ClkP2UduWZHt7lgEGVu1xCML

These are rough and need refinement because they're based off of an early version of dev, but the process should be nearly identical. I added way more to support than they expected, but from the perspective of, say, TFS administration all of the extra topics will be relevant.

Once the data models and custom fields are finalized I can move forward with a more detailed data import section. And once the CLF is in we can move forward with screenshots, and subsequently organizing the docs with sections, numbering, etc.

**Comment by jaysonmc** [comment]
For the user manual on the last page, could we please update the screenshot? We removed the modal view and went with just the list view, as I dont use a good use case for the panel view for our users.

Thanks. They look great! We'll aim to run them by some users in the near future.

**Comment by floo0025** [comment]
Technical Support Manual
https://drive.google.com/open?id=1o6TxmYYedc5Afe33J_Hoe4Imp_EKWAbO
