### ISSUE TITLE
How To - Data Import

### ISSUE THREAD

**Issue by jaysonmc** [gcdevops/HRWhiteListing#57]
Put in How To folder on Google Drive

**Comment by jaysonmc** [comment]
Put in How To folder on Google Drive

**Comment by floo0025** [comment]
User manual and support manula, v1, are up at https://drive.google.com/drive/folders/1YYTkeaX9ClkP2UduWZHt7lgEGVu1xCML

These are rough and need refinement because they're based off of an early version of dev, but the process should be nearly identical. I added way more to support than they expected, but from the perspective of, say, TFS administration all of the extra topics will be relevant.

Once the data models and custom fields are finalized I can move forward with a more detailed data import section. And once the CLF is in we can move forward with screenshots, and subsequently organizing the docs with sections, numbering, etc.

**Comment by floo0025** [comment]
Data import instructions, along with screenshots, are in the Support Manual at:

https://drive.google.com/open?id=1o6TxmYYedc5Afe33J_Hoe4Imp_EKWAbO
